/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Technologies",
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Chosen technologies for Start-UI",
      },
      items: [
        "technologies/typescript",
        "technologies/react",
        "technologies/nextjs",
        "technologies/react-router",
        "technologies/chakra-ui",
        "technologies/tanstack-query",
        "technologies/formiz",
        "technologies/storybook",
        "technologies/tooling",
        "technologies/others",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      link: {
        type: "generated-index",
        description: "Some guides for help you using Start-UI",
      },
      items: [
        "guides/update-theme-typing",
        "guides/generate-icons",
        "guides/development-mirage",
        "guides/remove-mirage",
        "guides/development-jhipster",
        "guides/api-documentation",
        "guides/hint-development-env",
        "guides/translations",
      ],
    },
  ],
};

module.exports = sidebars;
